"""Esquema inicial: las 11 tablas tal como estaban al adoptar Alembic (oct. 2026).

Revision ID: 0001
Revises:
Create Date: 2026-10-03

Generada con autogenerate sobre una base vacia. Una base nueva se crea aplicando
esta version; una anterior a Alembic se completa a mano hasta aqui y se marca como
0001 sin ejecutarla (ver app/plataforma/esquema.py).

Los triggers de proteccion de "transaction" no van aqui: los crea db.py en cada
arranque, con las columnas reales de la tabla.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate escribe tipos de sqlmodel)


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('debito', 'credito', 'billetera', 'efectivo', name='accounttype', native_enum=False, length=20), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('credit_limit_cents', sa.Integer(), nullable=True),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_name'), ['name'], unique=True)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('gasto', 'ingreso', 'transferencia', name='direction', native_enum=False, length=20), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_necessity', sa.Enum('esencial', 'discrecional', 'evitable', name='necessity', native_enum=False, length=20), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_category_name_parent')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=False)

    op.create_table('email_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Enum('parseado', 'sin_parser', 'ignorado', 'error', name='parsestatus', native_enum=False, length=20), nullable=False),
    sa.Column('parser', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_message_gmail_id'), ['gmail_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_message_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_message_sender'), ['sender'], unique=False)

    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sheet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('duplicated_count', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kv',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('saldo_corte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_cambio_diezmil', sa.Integer(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saldo_corte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saldo_corte_fecha'), ['fecha'], unique=True)

    op.create_table('transaction_papelera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('editado_por_usuario', sa.Boolean(), nullable=False),
    sa.Column('datos', sa.Text(), nullable=True),
    sa.Column('borrado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_papelera', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_papelera_dedupe_hash'), ['dedupe_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_papelera_email_id'), ['email_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_papelera_tx_id'), ['tx_id'], unique=False)

    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_category_id'), ['category_id'], unique=True)

    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('op', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_amount_cents', sa.Integer(), nullable=True),
    sa.Column('max_amount_cents', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('gasto', 'ingreso', 'transferencia', name='direction', native_enum=False, length=20), nullable=True),
    sa.Column('set_category_id', sa.Integer(), nullable=True),
    sa.Column('set_necessity', sa.Enum('esencial', 'discrecional', 'evitable', name='necessity', native_enum=False, length=20), nullable=True),
    sa.Column('set_merchant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('set_recurring', sa.Boolean(), nullable=True),
    sa.Column('stop', sa.Boolean(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['set_category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saldo_cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corte_id', sa.Integer(), nullable=False),
    sa.Column('cuenta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('es_deuda', sa.Boolean(), nullable=False),
    sa.Column('monto_cents', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corte_id'], ['saldo_corte.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corte_id', 'cuenta', 'moneda', name='uq_saldo_cuenta_corte')
    )
    with op.batch_alter_table('saldo_cuenta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saldo_cuenta_corte_id'), ['corte_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sa.Enum('gasto', 'ingreso', 'transferencia', name='direction', native_enum=False, length=20), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('counter_account_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('efectivo', 'debito', 'credito', 'yape', 'plin', 'transferencia', 'otro', name='paymentmethod', native_enum=False, length=20), nullable=True),
    sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merchant_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operation_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('necessity', sa.Enum('esencial', 'discrecional', 'evitable', name='necessity', native_enum=False, length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('gmail', 'manual', 'excel', name='source', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('confirmada', 'por_revisar', 'duplicada', 'ignorada', name='txstatus', native_enum=False, length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('parser', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('locked_by_user', sa.Boolean(), nullable=False),
    sa.Column('user_edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['counter_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email_message.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_dedupe_hash'), ['dedupe_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_transaction_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_merchant'), ['merchant'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_operation_number'), ['operation_number'], unique=False)
        batch_op.create_index('ix_tx_date_dir', ['booking_date', 'direction'], unique=False)
        batch_op.create_index('ix_tx_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Bajar de la version inicial es borrar todas las tablas, con tus datos dentro.
    raise RuntimeError("La version 0001 no se deshace: borraria todas las tablas.")
